# Generated by Django 5.0.6 on 2024-05-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=12)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=40)),
                ('telefone', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=40)),
                ('cidade', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=3)),
                ('cep', models.CharField(max_length=9)),
                
                

                
            ],
        ),
    ]








